# Generated by Django 5.0.6 on 2024-10-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.AlterModelTable(
            name='artist',
            table='artists',
        ),
    ]
