# Generated by Django 5.0.6 on 2024-10-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_rename_artists_artist_alter_artist_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
