# Generated by Django 5.0.6 on 2024-10-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_rename_firstname_artist_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
