# Generated by Django 5.0.6 on 2024-11-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_shows_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='Prices',
        ),
    ]
